# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-03 18:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=250)),
                ('Budget', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(max_length=100)),
                ('Lastname', models.CharField(max_length=100)),
                ('Age', models.IntegerField()),
                ('Project', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Lab.Project')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='Workers',
            field=models.ManyToManyField(blank=True, to='Lab.Worker'),
        ),
    ]
