# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-04 07:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Lab', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='Project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Lab.Project'),
        ),
    ]
